### ISSUE TITLE
Any update on fetching the focus keywords for posts, pages or custom post types?

### ISSUE THREAD

**Issue by zamanq** [niels-garve/yoast-to-rest-api#1]
Hello guys,
Nice work! I see the plugin was not updated for quite a long time and I find it very useful while developing decoupled wordpress sites using the WP Rest API. I was wondering if it is possible to work on the updates that you planned for this plugin i.e. adding the focus keywords fetching at least?

Thank you!

**Comment by Poliuk** [comment]
Hey @zamanq take a look to this other plugin https://github.com/maru3l/wp-api-yoast-meta it's an evolution of this one and it's being actively updated.

**Comment by zamanq** [comment]
@Poliuk  Thanks a lot!

**Comment by Poliuk** [comment]
Just in case someone ends up here, it looks like the plugin I mentioned in my previous question is not actively maintained anymore. In any case, my team has released this plugin https://wordpress.org/plugins/rest-api-head-tags/ and we plan to maintain it :)

**Comment by zamanq** [comment]
@Poliuk That looks promising, will try it! Thanks for letting us know, much appreciated!

**Comment by Poliuk** [comment]
You are welcome @zamanq, any feedback will be much appreciated!
