### ISSUE TITLE
What are the endpoints in the plugin?

### ISSUE THREAD

**Issue by coderbhaai** [niels-garve/yoast-to-rest-api#2]
I am not able to figure out the endpoints for the plugin.

Would be nice if the same is provided in the documentation for beginers.

**Comment by ghost** [comment]
@coderbhaai I have same issue, did you manage to figure out the endpoints for this plugin.

**Comment by coderbhaai** [comment]
@expatguideturkey
No,
I used better-rest-endpoints (https://github.com/factor1/better-rest-endpoints)

This has most of the endpoints that can be used for Yoast SEO... Let me know if you need nay help.

**Comment by ghost** [comment]
@coderbhaai thanks for sharing the plugin. Is there a way to extract focus keyword field of yoast seo. With this plugin I can only extract below fields:

 ```
wordpressPage(wordpress_id: {eq: 152070}) {
    yoast_meta {
      yoast_wpseo_canonical
      yoast_wpseo_metadesc
      yoast_wpseo_title
    }
  }
```

**Comment by Poliuk** [comment]
@coderbhaai @expatguideturkey my team has released a new plugin to expose head tags in the rest API, fully compatible with Yoast SEO and All in One SEO.

 You can take a look at it here: https://wordpress.org/plugins/rest-api-head-tags/

**Comment by ghost** [comment]
how to extract focus keyword field. it's not listed there.

**Comment by coderbhaai** [comment]
@expatguideturkey The focus keyword is showing. Try using Postman to check data you get in API Call and everything will be clear.
It appears as 
"yoast": {
            "yoast_wpseo_focuskw":

**Comment by niels-garve** [comment]
Hello everyone!
I am not maintaining this plugin anymore.
Please have a look a the README. I just added a link to the repository that I forked. They suggest a new plugin.
I'm closing here.
Sorry for the delay!
Kind regards
Niels

**Comment by Poliuk** [comment]
For anyone ending up here, I was one of the creators of the original plugin that it's not maintained anymore because we have released a new one: https://wordpress.org/plugins/rest-api-head-tags/

Thanks for your work @niels-garve

**Comment by niels-garve** [comment]
Thank you @Poliuk ! And amazing new plugin!
